# Generated by Django 3.1.7 on 2021-06-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oxygen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=25)),
                ('contact', models.BigIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('Verifed_status', models.BooleanField(default=False)),
                ('timestamp', models.TimeField()),
            ],
        ),
    ]
